apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-infisical-app
  namespace: testinginf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-infisical-app
  template:
    metadata:
      labels:
        app: fastapi-infisical-app
    spec:
      containers:
      - name: fastapi-infisical-app
        image: hemanth097/fastapi-infisical-app:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: infisical-secrets
